export const productsDB = [
  {
    title: "Aprende HTML: El Curso Completo Desde Cero",
    description: "Aprende HTML: El curso completo desde cero es un libro completo que te enseña todo lo que necesitas saber sobre HTML, desde los conceptos básicos hasta las etiquetas más avanzadas. A través de ejemplos interactivos y una explicación clara y concisa, aprenderás a utilizar las etiquetas HTML para crear sitios web atractivos y funcionales.",
    author: "Kiko Palomares",
    category: "HTML",
    price: 9.90,
    stock: 2,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687463881/ecommerce-libros/libro-html_nod6xt.jpg",
  },
  {
    title: "Transiciones y Animaciones Creativas en CSS",
    description: "Un guía que te permitirá realizar emocionantes experimentos con transiciones y animaciones en CSS, aplicándolos a una variedad de elementos, como botones, imágenes, textos y elementos HTML más complejos.",
    author: "Andrés Cruz Yoris",
    category: "CSS",
    price: 14.90,
    stock: 3,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687463881/ecommerce-libros/libro-css_grmbiw.jpg",
  },
  {
    title: "Aprendiendo JavaScript",
    description: "Aprende las bases del lenguaje web más demandado, desde cero hasta ECMAScript 6+. Partiremos desde las bases y poco a poco iremos ampliando hasta ver las nuevas características del lenguaje para hacer un uso profesional de él.",
    author: "Carlos Azaustre",
    category: "JavaScript",
    price: 19.90,
    stock: 5,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687463881/ecommerce-libros/libro-javascript_jdizns.jpg",
  },
  {
    title: "The Road to learn React (Spanish)",
    description: "Hay muchos caminos para aprender React. Este libro toma elementos de cada uno y crea una ruta, que te guiará directo a la implementación de una web app real. Construirás tu propia aplicación React y aprenderás sobre ES6, React, conceptos básicos y gestión interna de estado.",
    author: "Robin Wieruch",
    category: "React",
    price: 19.90,
    stock: 0,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687463881/ecommerce-libros/libro-react-1_rbsg00.jpg",
  },
  {
    title: "React: Preguntas típicas",
    description: "+100 preguntas típicas de React. Explicadas y detalladas. Con ejemplos de código.",
    author: "Miguel Ángel Durán",
    category: "React",
    price: 9.90,
    stock: 2,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687463881/ecommerce-libros/libro-react-2_ty9mor.jpg",
  },
  {
    title: "Descubre Svelte",
    description: "Svelte es un soplo de aire fresco en el mundo del Desarrollo Web, dominado por React, Angular y Vue. Apuesta por evitar que escribas código repetitivo e inútil. Su sencillez hará que vuelvas a amar la Programación Web.",
    author: "Miguel Ángel Durán",
    category: "Svelte",
    price: 9.90,
    stock: 3,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687463881/ecommerce-libros/libro-svelte_kgo4uu.jpg",
  },
  {
    title: "Programador y Diseño Web 1: Conceptos Básicos",
    description: "Este libro brinda los conceptos básicos necesarios para sumergirse en el apasionante universo de la programación web. Encontrarás los conceptos básicos en programación con HTML5, CSS3 y Php. Contiene además definiciones y muestras gráficas.",
    author: "Aljandro M. Medrano",
    category: "HTML",
    price: 9.90,
    stock: 4,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687714521/ecommerce-libros/libro-html-css-php_i6tytm.jpg",
  },
  {
    title: "Desarrollo Web de Principiante a Profesional con Paga",
    description: "La credibilidad de un desarrollador web es mucho más que sus credenciales. En realidad, se trata del peso de su portafolio. Este libro no solo te ayudará a aprender bien y a crear un portafolio impresionante, sino que también te proporcionará ayuda y apoyo continuo.",
    author: "Ojula Technology Innovations",
    category: "HTML",
    price: 28.90,
    stock: 3,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687714822/ecommerce-libros/libro-html-css-javascript_ax4hai.jpg",
  },
  {
    title: "7 Días de HTML",
    description: "¡Da el primer paso hacia el mundo del desarrollo web con '7 días de HTML'! Esta guía fácil de seguir te llevará desde los conceptos básicos hasta el dominio de HTML, el lenguaje de marcado esencial en el desarrollo web, en solo una semana.",
    author: "Kiko Palomares",
    category: "HTML",
    price: 9.90,
    stock: 3,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687715043/ecommerce-libros/libro-html-2_iylut5.jpg",
  },
  {
    title: "Maestro del Desarrollo Front-end",
    description: "Este libro está diseñado para guiarte en tu viaje hacia la maestría en desarrollo front-end. A través de sus páginas, aprenderás los conceptos básicos y avanzados del desarrollo front-end, incluyendo HTML, CSS, Tailwind, JavaScript, Typescript, React, Angular y cómo integrarlos para crear aplicaciones web atractivas y eficientes.",
    author: "RIBAPPS",
    category: "HTML",
    price: 22.90,
    stock: 2,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687715231/ecommerce-libros/libro-html-css-javascript-react-angular_gsorje.jpg",
  },
  {
    title: "10 KATA DEL DESARROLLO FRONTEND",
    description: "Kata, palabra japonesa que representa una secuencia de movimientos establecidos que se realizan con la finalidad de perfeccionar una técnica. Esta referencia quiero transmitirla a ustedes en el ámbito del desarrollo frontend, intentando crear una serie de conceptos y técnicas que deben adquirirse y perfeccionarse por cada nivel de aprendizaje.",
    author: "José MARIN",
    category: "HTML",
    price: 14.90,
    stock: 0,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687715507/ecommerce-libros/libro-html-css-javascript-react_on88wp.jpg",
  },
  {
    title: "Frontend Testing",
    description: "¿Desarrollas para la web? ¿Quieres aprender a escribir tests pero no sabes por dónde empezar? En este libro se explican los conceptos básicos de Testing en Front-End a través de ejemplos y casos prácticos.",
    author: "Iago Lastra Rodríguez",
    category: "Testing",
    price: 7.90,
    stock: 3,
    image: "https://res.cloudinary.com/dwqk2mkgh/image/upload/f_auto,q_auto/v1687715657/ecommerce-libros/libros-testing_smqt8s.jpg",
  },
]